version: "3.8"
services:
  skybridge:
    container_name: "skybridge"
    image: #docker image, use the one pointed in the readme.
    restart: always
    volumes:
      - skybridge:/app/database
    environment:
      # Base URL of where SkyBridge will be hosted without the protocol. Reverse proxy URL
      - SKYBRIDGE_BASEURL=
      # Random secret, generate with `openssl rand -base64 32`.
      - SKYBRIDGE_SECRET=
      # Password used to make a SkyBridge instance private.
      - SKYBRIDGE_AUTH_PASSWORD=
      # Should a bridge password be required to authenticate?
      - SKYBRIDGE_REQUIRE_AUTH_PASSWORD=true
      # Should a nice index page be shown on the root URL?
      - SKYBRIDGE_SHOW_INDEX=false
      # Allow backfilling/scrolling on timelines? (can cause issues on instances under heavy load)
      - SKYBRIDGE_ALLOW_BACKFILL=true
    ports:
      - "8080:8080" #feel free to adjust the left side if localhost:8080 on your NAS is already in use.

volumes:
  skybridge:
