name: sky_bridge
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  atproto: ^1.4.1
  bluesky: ^1.4.1
  bluesky_text: ^0.6.4
  collection: ^1.17.1
  copy_with_extension: ^5.0.2
  crypto: ^3.0.2
  dart_frog: ^1.2.0
  dart_jsonwebtoken: ^2.8.2
  dcli_core: ^3.0.3
  dotenv: ^4.1.0
  html: ^0.15.3
  http: ^1.2.0
  image: ^4.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  orm: ^4.4.0
  path: ^1.8.3
  shelf_cors_headers: ^0.1.5
  shelf_rate_limiter: ^1.0.1
  template_expressions: ^3.0.0+5
  yet_another_json_isolate: ^1.0.4

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.2
  fixnum: ^1.1.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
